apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Svar på mer oppfølging"
    dcat.data.nav.no/description: >-
      Topic inneholder svar fra sykmeldte om de ønsker mer oppfølging fra Nav.
  name: sen-oppfolging-svar
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: team-esyfo
      application: meroppfolging-backend
      access: write
    - team: teamsykefravr
      application: isyfomock
      access: write
    - team: teamsykefravr
      application: ismeroppfolging
      access: read
