style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
config:
  validation: true
  warningsAsErrors: true
exceptions:
  TooGenericExceptionCaught:
    active: false
complexity:
  LongParameterList:
    active: false
