spring:
  main.banner-mode: 'off'
  profiles:
    active: default

management:
  endpoint:
    prometheus.enabled: true
    health.probes.enabled: true
    health.show-details: always
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus
  health:
    livenessState.enabled: true
    readinessState.enabled: true

logging.config: "classpath:logback.xml"

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
