apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: meroppfolging-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 600Mi
  vault:
    enabled: false
  kafka:
    pool: nav-dev
  ingresses:
    - "https://meroppfolging-backend.intern.dev.nav.no"
  leaderElection: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: meroppfolging-frontend
  env:
    - name: MEROPPFOLGING_FRONTEND_CLIENT_ID
      value: "dev-gcp:team-esyfo:meroppfolging-frontend"
