apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: meroppfolging-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/health/readinessState
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: meroppfolging-backend-db
            envVarPrefix: DB
        diskAutoresize: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 600Mi
  vault:
    enabled: false
  kafka:
    pool: nav-prod
  ingresses:
    - "https://meroppfolging-backend.intern.nav.no"
  leaderElection: true
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: meroppfolging-frontend
        - application: esyfo-proxy
        - application: syfomodiaperson
          namespace: teamsykefravr
    outbound:
      rules:
        - application: syfooppdfgen
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
        - application: istilgangskontroll
          namespace: teamsykefravr
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
        - application: sykepengedager-informasjon
        - application: digdir-krr-proxy
          namespace: team-rocket
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
  env:
    - name: MEROPPFOLGING_FRONTEND_CLIENT_ID
      value: "prod-gcp:team-esyfo:meroppfolging-frontend"
    - name: ESYFO_PROXY_CLIENT_ID
      value: "prod-gcp:team-esyfo:esyfo-proxy"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: http://isoppfolgingstilfelle.teamsykefravr
    - name: ISOPPFOLGINGSTILFELLE_ID
      value: prod-gcp:teamsykefravr:isoppfolgingstilfelle
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: ISTILGANGSKONTROLL_ID
      value: prod-gcp.teamsykefravr.istilgangskontroll
    - name: SYFOBEHANDLENDEENHET_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet.teamsykefravr"
    - name: SYFOOPPDFGEN_URL
      value: http://syfooppdfgen
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: prod-fss.teamdokumenthandtering.dokarkiv
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: prod-fss.pdl.pdl-api
    - name: TOGGLE_SSPS_VARSELUTSENDING
      value: "true"
    - name: DKIF_URL
      value: http://digdir-krr-proxy.team-rocket/rest/v1/person
    - name: DKIF_SCOPE
      value: prod-gcp.team-rocket.digdir-krr-proxy
    - name: SEND_VARSEL_JOB_CRON
      value: 0 0 9-17 * * *
