apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: meroppfolging-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/health/readinessState
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: meroppfolging-backend-db
            envVarPrefix: DB
        diskAutoresize: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 600Mi
  vault:
    enabled: false
  kafka:
    pool: nav-dev
  ingresses:
    - "https://meroppfolging-backend.intern.dev.nav.no"
  leaderElection: true
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: meroppfolging-frontend
        - application: esyfo-proxy
        - application: syfomodiaperson
          namespace: teamsykefravr
    outbound:
      rules:
        - application: esyfovarsel
        - application: syfooppdfgen
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
        - application: istilgangskontroll
          namespace: teamsykefravr
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
        - application: veilarbregistrering
          namespace: paw
        - application: sykepengedager-informasjon
      external:
        - host: dokarkiv.dev-fss-pub.nais.io
  env:
    - name: MEROPPFOLGING_FRONTEND_CLIENT_ID
      value: "dev-gcp:team-esyfo:meroppfolging-frontend"
    - name: ESYFO_PROXY_CLIENT_ID
      value: "dev-gcp:team-esyfo:esyfo-proxy"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: http://isoppfolgingstilfelle.teamsykefravr
    - name: ISOPPFOLGINGSTILFELLE_ID
      value: dev-gcp:teamsykefravr:isoppfolgingstilfelle
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: ISTILGANGSKONTROLL_ID
      value: dev-gcp.teamsykefravr.istilgangskontroll
    - name: ESYFOVARSEL_URL
      value: http://esyfovarsel
    - name: ESYFOVARSEL_ID
      value: dev-gcp:team-esyfo:esyfovarsel
    - name: SYFOBEHANDLENDEENHET_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet.teamsykefravr"
    - name: VEILARBREGISTRERING_URL
      value: http://veilarbregistrering.paw
    - name: VEILARBREGISTRERING_ID
      value: dev-gcp:paw:veilarbregistrering
    - name: SEND_TO_VEILARBREGISTRERING_TOGGLE
      value: "false"
    - name: TOGGLE_PILOT
      value: "true"
    - name: SYFOOPPDFGEN_URL
      value: http://syfooppdfgen
    - name: DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: dev-fss.teamdokumenthandtering.dokarkiv
