CREATE TABLE KARTLEGGINGSPORSMAL_KANDIDAT
(
    KANDIDAT_ID UUID PRIMARY KEY NOT NULL,
    FNR VARCHAR(11) NOT NULL,
    STATUS TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL
);

ALTER TABLE KARTLEGGINGSPORSMAL
ADD COLUMN KANDIDAT_ID UUID NOT NULL;
