CREATE TABLE KARTLEGGINGSPORSMAL
(
    UUID UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    FNR VARCHAR(11) NOT NULL,
    FORM_SNAPSHOT JSONB NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL
);
