ALTER TABLE SKIP_VARSELUTSENDING
ADD COLUMN reason VARCHAR(32);

UPDATE SKIP_VARSELUTSENDING
SET reason = 'AGE'
WHERE reason IS NULL;

ALTER TABLE SKIP_VARSELUTSENDING
ALTER COLUMN reason SET NOT NULL;

ALTER TABLE SKIP_VARSELUTSENDING
ADD CONSTRAINT skip_varselutsending_person_ident_unique UNIQUE (person_ident);
