ALTER TABLE KARTLEGGINGSPORSMAL_KANDIDAT
    DROP COLUMN IF EXISTS SKJEMAVARIANT;

DROP TYPE IF EXISTS SKJEMAVARIANT_ENUM;

ALTER TABLE KARTLEGGINGSPORSMAL_KANDIDAT
    ADD COLUMN SKJEMAVARIANT VARCHAR(255) NOT NULL DEFAULT 'FLERVALG_V1';
