ALTER TABLE JOURNALFORING_FAILED
    ADD CONSTRAINT constraint_name UNIQUE (varsel_uuid);

ALTER TABLE JOURNALFORING_FAILED
    ALTER COLUMN pdf DROP NOT NULL;

CREATE UNIQUE INDEX varsel_uuid_index ON SYKEPENGEDAGER_INFORMASJON (varsel_uuid);
